name: Test app

on:
  push:
    branches:
      - main

jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main

      - name: Install golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod download

      - name: Clear test cache
        run: |
          go clean -testcache

      - id: setup-buildpack-tools
        name: install tools for build pack
        uses: buildpacks/github-actions/setup-tools@v5.1.0

      - id: setup-pack
        name: install client for build pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.43.0

      - name: copy local settings
        run : just copy-settings

      - name: Build with Pack
        run: |
          just docker-build

      - name: Run service
        run: |
          docker compose -f compose.test.yaml up -d

      - name: Run test
        run: |
          go test -v ./integration-tests

      - name: Drop service
        run: |
          docker compose -f compose.test.yaml down -v

      - id: image-clear
        name: remove all images
        run: docker rmi --force $(docker images -q)

