name: Test app

on:
  push:
    branches:
      - main

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main

      - name: Install golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod download

      - id: setup-buildpack-tools
        name: install tools for build pack
        uses: buildpacks/github-actions/setup-tools@v5.1.0

      - id: setup-pack
        name: install client for build pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.43.0

      - name: Build with Pack
        run: |
          just docker-build

      - name: Run test
        run: |
          just test

      - id: image-clear
        name: remove all images
        run: docker rmi --force $(docker images -q)

